//
//  DataStore.swift
//  SoulsView
//
//  Created by Mikolaj Witkowski on 16/05/2020.
//  Copyright © 2020 Mikolaj Witkowski. All rights reserved.
//

import SwiftUI

struct CharacterData {
    var name: String
    var portraitImageString: String
    var backgroundImageString: String
    var description: [String]
    var id = UUID()
}

let characters = [artorias, capra, friede, gravelordNito, gwyn, ornstein, quelaag]

let artorias = CharacterData(name: "Artorias, The Abysswalker", portraitImageString: "Artorias", backgroundImageString: "ArtoriasBackground", description: ["Sir Artorias the Abysswalker was one of the Four Knights of Lord Gwyn. He only makes an appearance in the past, as he is deceased by the time the Chosen Undead escapes the Undead Asylum. He is known to have been a friend to Alvina of the Forest Hunter covenant. Sif, the Great Grey Wolf was his companion, now guarding his grave and keeping the Covenant of Artorias ring in his possession.", "Artorias hunted the Darkwraiths and was able to traverse the Abyss with the power of his ring, which he obtained after making a covenant with the beasts there, preventing him from being swallowed by the void, but cursing his sword in the process. In recognition of his actions, he was awarded one of Anor Londo's treasures - a Silver Pendant that allowed him to repel Dark sorceries."])

let friede = CharacterData(name: "Sister Friede", portraitImageString: "Friede", backgroundImageString: "FriedeBackground", description: ["Friede is the eldest of the three sisters who founded the Sable Church of Londor, the others being Yuria and Liliane. Sister Friede is an Unkindled, suggesting that she attempted to link the First Flame or usurp it but failed, resulting in her being resurrected as ash.", "Having abandoned the Sable Church, she happened upon Ariandel's Painted World. There, she tricked Father Ariandel by convincing him that the only way to preserve the Painted World was by suppressing the fire with his own blood to prevent it from being burned to the ground, and resulting in the rot that afflicts it.", "Despite giving ample warning, Sister Friede is ultimately forced to wield her scythe and confront the meddling Ashen One, not before asking Father Ariandel to turn his gaze away from the imminent carnage. When she collapses the first time, an enraged Ariandel sparks the flame he bled so much to prevent in a desperate attempt to revive her. Now rekindled, she comes back from death to fight by his side. After falling a second time, Friede rises yet again and tinges her flame black with the Dark in one final struggle to defeat the second ash and prevent the painted world from being eventually replaced with a new one."])

let gwyn = CharacterData(name: "Gwyn, Lord of Cinder", portraitImageString: "Gwyn", backgroundImageString: "GwynBackground", description: ["Before the flame existed, little of Gwyn's life is known, save that he had an uncle named Lloyd. He was surrounded by knights when he found the flame, and was dressed in his regalia, so it is possible that he may have been a king long before that moment. At the dawn of the Age of Fire, Gwyn discovered a Lord Soul along with the Furtive Pygmy, Gravelord Nito, and the Witch of Izalith. His soul allowed him to manipulate light, and generate a substance called lightning. They allied with Seath the Scaleless and amassed an army, and with their power, challenged the Everlasting Dragons for dominion of the World. His mighty bolts peeled apart their ancient scales, allowing them to be killed by other attacks, and they were ultimately defeated, but not eliminated.", "Lord Gwyn wears an impressive set of royal drapes, with gold bands on his arms, and a crown atop his head. On his feet are what appear to be a form of moccasins and anklets, and he wields a greatsword imbued with the power of light and of the First Flame, which he uses to adequate effect. His face is that of an aged man with calm eyes, and he has an impressively long, grey beard and hair of the same nature. When the Chosen Undead fights Gwyn in the Kiln of the First Flame, Gwyn appears to be Hollow, evident by his haggard appearance, charred skin and missing eyes.", "And thus the Age of Fire began, with Gwyn becoming the king of Lordran. He lived with his clan, who became a new and varied race known as Gods, in their city of Anor Londo. They often hunted the descendants of the dragons for sport, for which many of their powers were developed. This did not include Seath, for he received recognition for his deeds, and was made a part of the nobility."])

let ornstein = CharacterData(name: "Dragonslayer Ornstein", portraitImageString: "Ornstein", backgroundImageString: "OrnsteinBackground", description: ["Ornstein was one of Lord Gwyn's most trusted knights, who was also loyal to Lord Gwyn's Firstborn. Believed to be the captain of the Four Knights of Gwyn, he was granted a special soul and ring by the Lord of Sunlight.", "His golden armor was made to resemble a lion and was imbued with the power of lightning. It is said that his lugged spear could slice a boulder in two. After the gods fled Anor Londo, Ornstein and Executioner Smough were stationed to guard its cathedral, and the princess of sunlight within it.", "At some point, Ornstein left the cathedral in search of the Nameless King. It is unclear how Ornstein survived the battle against the Chosen Undead, but it appears he eventually found his way to Archdragon Peak. However, the results of his search, as well as Ornstein's own fate, remains unknown."])

let gravelordNito = CharacterData(name: "Gravelord Nito", portraitImageString: "GravelordNito", backgroundImageString: "GravelordNitoBackground", description: ["Nito, the first of the dead, is one of the original Lords who found a Lord Soul at the dawn of the Age of Fire. His soul turned him into a living manifestation of illness and death, a mass of skeletons held together. He, along with the other Lords, waged war against the Dragons, and helped issue the killing blow by unleashing a miasma of death and disease upon them.", "After the war with the dragons, Nito descended into the Catacombs, and slumbered within the Tomb of the Giants. Even in that state, he could administer the death of all life and offered much of the energy of his own soul to death itself. Travelers brave enough to find their way into his tomb would pay their respects and become a Gravelord Servant. They would use the Eyes of Death to cause hostile spirits to invade other worlds, spreading death throughout them, which allowed the multiplication of the Eyes of Death, which in turn allows death to increase exponentially. While Nito sees all death, and induces all death, his servants return with Eyes of Death to prove that they have done their tasks[4]. In return for their service to him, Nito accepts these offerings, and presents his servants with more power.", ""])

let capra = CharacterData(name: "Capra Demon", portraitImageString: "Capra", backgroundImageString: "CapraBackground", description: ["Capra Demons were demons that were most likely created when the Witch of Izalith attempted to duplicate the First Flame using a Lord Soul. The attempt was unsuccessful and accidentally created the Bed of Chaos, the mother and source of all demons. Capra Demons were classed as lesser demons. One eventually inhabited the lower section of the Undead Burg, a fortified town that devolved into ruin. Meanwhile, others came to house the area known as the Demon Ruins, the gateway to Lost Izalith.", "The Chosen Undead encountered the aforementioned lone Capra Demon, when they explored the Undead Burg on their pilgrimage. The demon was accompanied by a pair of Attack Dogs but the Chosen Undead nonetheless defeated all three beasts in combat. From the demon's possession, the Undead acquired the key to the Depths. The Undead Male Merchant referred to the lone Capra Demon as a goat demon when he remarked about the Burg's treacherous nature. Later, the Chosen Undead came across more Capra Demons when they journeyed through the Demon Ruins to reach the fallen city of Lost Izalith.", ""])

let quelaag = CharacterData(name: "Chaos Witch Quelaag", portraitImageString: "Quelaag", backgroundImageString: "QuelaagBackground", description: ["Queelag is a daughter of the Witch of Izalith and, along with most of her family, failed to escape from the chaotic flame and was corrupted by it. Due to exposure to the flame, Quelaag and her sister mutated into spider-like creatures with their upper body being fused to the monsters' backs.", "She is the Fair Lady's older sister. When their mother, the Witch of Izalith along with their other two sisters became the Bed of Chaos, she fled with her sister. Although their sanity is intact, their lower bodies became bound with demon spiders. When her sister became weakened and blind, Quelaag remained in Blighttown to protect her from anyone or anything that would try to harm her.", ""])
